
spring:
  profiles:
    active: dev

#cache: false  #开发者工具dev-tools激活后，如下属性会设置为false。
# spring.thymeleaf.cache
# spring.freemarker.cache
# spring.velocity.cache
# spring.mustache.cache
# spring.groovy.template.cache
  thymeleaf:
    cache: false

#数据库配置
## 配置获取连接等待超时的时间
#spring.datasource.maxWait=60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#spring.datasource.timeBetweenEvictionRunsMillis=60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
## 打开PSCache，并且指定每个连接上PSCache的大小
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#spring.datasource.filters=stat,wall,log4j
## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
## 合并多个DruidDataSource的监控数据
##spring.datasource.useGlobalDataSourceStat=true
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#spring.datasource.filters=stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据


## 加密后的密码（原密码 123456）
#spring.datasource.password=WVMjPhfXQrIsWRo0/RCqAVvYtTU9WNVToKJohb8AlUmHwnV6vwFL+FM2CNFDMJwGHW1iCmyaUlF+sgvFdogqEA==
## 公钥
#publickey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIiwHpFrDijV+GzwRTzWJk8D3j3jFfhsMFJ/7k1NTvBuLgL+TdIHgaMNOIEjHpXzuvX38J3FtOK8hLrySncVGOMCAwEAAQ==
## 配置 connection-properties，启用加密，配置公钥。
#spring.datasource.druid.connection-properties=config.decrypt=true;config.decrypt.key=${publickey}
## 启动ConfigFilter
#spring.datasource.druid.filter.config.enabled=true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.221:3307/spring_boot_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bestsign
    password: ssqian2016
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



########################################################
###REDIS (RedisProperties) redis基本配置；
########################################################
# database name
#spring.redis.database=0
# server host1
#spring.redis.host=127.0.0.1
# server password
#spring.redis.password=
#connection port
#spring.redis.port=6379
#pool settings ...
#spring.redis.pool.max-idle=8
#spring.redis.pool.min-idle=0
#spring.redis.pool.max-active=8
#spring.redis.pool.max-wait=-1
# name of Redis server
#spring.redis.sentinel.master=
# comma-separated list of host:port pairs
#spring.redis.sentinel.nodes=

#  redis:
#    database: 0
#    host: 192.168.1.91
#    port: 6379
#    password: feibaredis
#    pool:
#      max-active: 8
#      min-idle: 0
#      max-wait: -1
#      max-idle: 8

server:
  port: 8000
  servlet:
    session:
      cookie:
        http-only: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: false


#logging:
#  path: D:/
#  file: D:/spring_boot_test.log
#  level:
#    com.sqshine: DEBUG
#    com.sqshine.readinglist.domain.mapper: TRACE   # 输出mybatis的sql语句。


#DevTools
restart.
