spring:
  profiles:
    active: test
#  jackson:
#    default-property-inclusion: non_null
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

# 日志使用自定义的logback-spring.xml文件后，application.properties中关于日志的相关配置一些硬性的配置，例如生成日志文件等不会被影响，但是如果随意配置的话，会影响到自定义日志配置文件中的配置。
# 所以，配置了自定义的日志配置文件logback-spring.xml之后，就不用在application.properties进行配置了，不然多此一举，产生不必要的影响。
#logging:
#  level:
#    root: debug
#    com.sqshine: DEBUG
#    com.sqshine.readinglist.domain.mapper: TRACE   # 输出mybatis的sql语句。
#  file: logs/spring_boot_test.log

mybatis:
  type-aliases-package: com.sqshine.readinglist.domain.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: reuse

#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: false


---

spring:
  profiles: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#cache: false  #开发者工具dev-tools激活后，如下属性会设置为false。
# spring.thymeleaf.cache
# spring.freemarker.cache
# spring.velocity.cache
# spring.mustache.cache
# spring.groovy.template.cache
  thymeleaf:
    cache: false

#数据库配置
## 配置获取连接等待超时的时间
#spring.datasource.maxWait=60000
## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#spring.datasource.timeBetweenEvictionRunsMillis=60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#spring.datasource.minEvictableIdleTimeMillis=300000
#spring.datasource.validationQuery=SELECT 1 FROM DUAL
#spring.datasource.testWhileIdle=true
#spring.datasource.testOnBorrow=false
#spring.datasource.testOnReturn=false
## 打开PSCache，并且指定每个连接上PSCache的大小
#spring.datasource.poolPreparedStatements=true
#spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#spring.datasource.filters=stat,wall,log4j
## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
## 合并多个DruidDataSource的监控数据
##spring.datasource.useGlobalDataSourceStat=true
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#spring.datasource.filters=stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#spring.datasource.connectionProperties=druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# 合并多个DruidDataSource的监控数据


## 加密后的密码（原密码 123456）
#spring.datasource.password=WVMjPhfXQrIsWRo0/RCqAVvYtTU9WNVToKJohb8AlUmHwnV6vwFL+FM2CNFDMJwGHW1iCmyaUlF+sgvFdogqEA==
## 公钥
#publickey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIiwHpFrDijV+GzwRTzWJk8D3j3jFfhsMFJ/7k1NTvBuLgL+TdIHgaMNOIEjHpXzuvX38J3FtOK8hLrySncVGOMCAwEAAQ==
## 配置 connection-properties，启用加密，配置公钥。
#spring.datasource.druid.connection-properties=config.decrypt=true;config.decrypt.key=${publickey}
## 启动ConfigFilter
#spring.datasource.druid.filter.config.enabled=true

# durid  数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.221:3307/spring_boot_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bestsign
    password: ssqian2016
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


mapper:
  mappers:
      - com.sqshine.readinglist.util.BaseMapper
  not-empty: false
  identity: MYSQL


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

########################################################
###REDIS (RedisProperties) redis基本配置；
########################################################
# database name
#spring.redis.database=0
# server host1
#spring.redis.host=127.0.0.1
# server password
#spring.redis.password=
#connection port
#spring.redis.port=6379
#pool settings ...
#spring.redis.pool.max-idle=8
#spring.redis.pool.min-idle=0
#spring.redis.pool.max-active=8
#spring.redis.pool.max-wait=-1
# name of Redis server
#spring.redis.sentinel.master=
# comma-separated list of host:port pairs
#spring.redis.sentinel.nodes=

#  redis:
#    database: 0
#    host: 192.168.1.91
#    port: 6379
#    password: feibaredis
#    pool:
#      max-active: 8
#      min-idle: 0
#      max-wait: -1
#      max-idle: 8



#DevTools

---

spring:
  profiles: prod
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# Hikari数据源配置，需要去掉druid-spring-boot-starter才支持
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.221:3307/spring_boot_test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: bestsign
    password: ssqian2016
    #hikari参数配置，其他参数一般用默认即可
    hikari:
      maximum-pool-size: 15 #连接池最大连接数: cpu核心数*2 + 硬盘数, 默认10 一个连接池一般来讲连接数在10-20个, 根据部署的应用程序数量可以推测出mysql的max_connections值
      max-lifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      read-only: false  #是否是只读数据源, 做读写分离时有用, 保证slave数据源的安全
      #connection-timeout: #等待连接池分配连接的最大时长 30s, 如果超过这个时间还没有分配到连接, commit会抛异常
mapper:
  mappers:
      - com.sqshine.readinglist.util.BaseMapper
  not-empty: false
  identity: MYSQL


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

---
spring:
  profiles: test
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/workspace/h2db/spring_boot_test;MODE=MYSQL
    #url: jdbc:h2:mem:spring_boot_test;MODE=MYSQL
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8081

# 日志使用自定义的logback-spring.xml文件后，application.properties中关于日志的相关配置一些硬性的配置，例如生成日志文件等不会被影响，但是如果随意配置的话，会影响到自定义日志配置文件中的配置。
# 所以，配置了自定义的日志配置文件logback-spring.xml之后，就不用在application.properties进行配置了，不然多此一举，产生不必要的影响。
#logging:
#  level:
#    root: debug
#    com.sqshine: DEBUG
#    com.sqshine.readinglist.domain.mapper: TRACE   # 输出mybatis的sql语句。
#  file: logs/spring_boot_test.log


mapper:
  mappers:
      - com.sqshine.readinglist.util.BaseMapper
  not-empty: false
  identity: h2


pagehelper:
  helper-dialect: h2
  reasonable: true
  support-methods-arguments: true
  params: count=countSql