server:
  port: 9090
#  context-path: /boot
book:
  author: sqshine
  name: spring boot
  
spring:
  datasource:
    type: 
  output:
    ansi:
      enabled: detect
  profiles:
    active: prod
      


#logging:
#  file: E:/log/aaa.log

#级别控制
#logging:
#  level:
#    ROOT: INFO
#    org.springframework.web: INFO
#    org.springframework.security: DEBUG
#    org.springframework.cloud: DEBUG
